<html>
<head>
	<title>plantilla de la cafeteria para empleados </title>
	<link rel="stylesheet" href="plantilla_con.css">
</head>
<body style="background-color:#6C451C; margin:0px; padding:0px;">
<?php

	function CabeceraPagina()
	{
		
?> 
    
	<div class="divicion_arriba">
		<div class="logo">
			<img src="logo2.png" id="logo_imagen" width="65px" height="65px">
		</div>
		<div class="titulo_menu">
			<div class="titulo" style="margin-left:35px;">𓂀 C𝕒𝕗𝕖𝕥𝕖𝕣í𝕒 L𝕦𝕟𝕒 𝕪 S𝕠𝕞𝕓𝕣𝕒 𓂀</div>
			<div class="menu_navegacion" style="margin-right:10px;">
				<a href="empleado.php">Encuesta</a>
				<a href="comentarios.php">Comentarios</a>
				<a href="confi.php">Pedidos</a>
				<a href="index_2.php">Salir</a>
			</div>
			
		</div>
		<hr>
	</div>
	<hr>
<?php
	}
	function piePagina()
	{
?>
	<hr>
	<div class="divicion_abajo" style="color: white;">
		<div class="logo">
			<img src="logo2.png" id="logo_imagen" width="65px" height="65px">
		</div>
		<div style="margin-left:10%;font-size: 20px;">
			Telefono: 7721698081<br>
		</div>
		<div style="margin-left:5%;font-size: 20px;">
			Correo Electronico: CafeLunaYSombra@grupobakal.com<br>
		</div>
		<div style="margin-left:5%;font-size: 20px;">
			Horarios: de 8AM a 9PM <br>
		</div>
		
		
	</div>
<?php
	}
?>
</body>
</html>
